let tank = 30;
let distance = 0;

const petrol = [1,2,3,4,5];

function generateRandom() {
    return Math.ceil(Math.random() * 6);
}

while (distance <= 100 && tank >= 0) {
    // Generating Random Number
    let travel = generateRandom();
    
    if (tank > travel) {
        // If fuel is enough to cover the distance generated by random number
        tank -= travel;
        distance += travel;
    } else {
        // If fuel is not enough to cover the distance generated by random number
        console.log("Random Number : " + travel);
        distance += tank;
        tank = 0;
        console.log("Distance : " + distance);
        console.log("Remaining Petrol : 0");
        break;
    }

    /// Sharing the output
    console.log("Random Number : " + travel);
    console.log("Distance : " + distance);
    console.log("Remaining Petrol : " + tank);

    //if (petrol.includes(distance)) {
    if (distance in petrol) {
        tank += 20;
        console.log("--- 20 Liters Filled ---");
    }

    console.log("");
}
